__version__ = "0.0.3" # 20260120


from ThreeThreadsTool_heavymodel_on_videostream.ModelThread_module import ModelThread
from ThreeThreadsTool_heavymodel_on_videostream.VideoGet_module import VideoGet
from ThreeThreadsTool_heavymodel_on_videostream.VideoShow_module import VideoShow
from ThreeThreadsTool_heavymodel_on_videostream.FrameQueue_module import Queue
from ThreeThreadsTool_heavymodel_on_videostream.MainLoop_module import ThreeThreadsTool

